services:
  - type: web
    name: sms-bulk-backend
    env: node
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /health
